// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2IZgFh_Vj5ZKjy-ZawSBz5Irn5Oej8NA',
    appId: '1:974579607444:web:cf6dc35713fa0887de9181',
    messagingSenderId: '974579607444',
    projectId: 'new-small-hurry',
    authDomain: 'new-small-hurry.firebaseapp.com',
    storageBucket: 'new-small-hurry.appspot.com',
    measurementId: 'G-ZWV01BS4HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgQ6vvQ4kprtanS4hOVkffmHH5zxBI8Q',
    appId: '1:974579607444:android:6770511fd9a1343ede9181',
    messagingSenderId: '974579607444',
    projectId: 'new-small-hurry',
    storageBucket: 'new-small-hurry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnRlwBSXVHl2WsJXW0-WcNtOQ2h-_iQuA',
    appId: '1:974579607444:ios:483bfb356c8afd69de9181',
    messagingSenderId: '974579607444',
    projectId: 'new-small-hurry',
    storageBucket: 'new-small-hurry.appspot.com',
    androidClientId: '974579607444-krmkvo398f5udd24g1apioe2q1ps7g6t.apps.googleusercontent.com',
    iosClientId: '974579607444-ddiium2qtr8ugpb54t0rdh87llv7f4l9.apps.googleusercontent.com',
    iosBundleId: 'com.smallhurry.app',
  );
}
